### ISSUE TITLE
Process Step Representation in ISO

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [ternaustralia/TERN-ISO19115#13]
How7: This is the process steps, which previously was in its own resourceLineage element.  Just confirming; it should now be included in the same resourceLineage element as the procedure details (How1-4)?

**Comment by kitchenprinzessin3880** [comment]
MD_Metadata(https://wiki.esipfed.org/MD_Metadata) has mdb:resourceLineage, which has  zero or more mrl:LI_Lineage (https://wiki.esipfed.org/LI_Lineage). all process steps should in the same resourceLineage element as the processes elaborate the summary of the data creation (represented by mrl:statement ).

**Comment by markhepburn** [comment]
Still trying to nail down the mapping -- so if we have a single resourceLineage (/LI_Lineage) element, it has a single mrl:statement child.  In the UI that is mapped to How2 (summary of the procedure details).

We also have the optional data creation procedure *steps* section, and the description field there (How7) previously mapped to the mrl:statement element in the _second_ resourceLineage element.  If we only have a single resourceLineage element, how should we reconcile the overlap?

**Comment by kitchenprinzessin3880** [comment]
@markhepburn process steps do not have description - only process steps are captured - deva will update you with the GUI changes (i spotted it yesterday when reviewing the product spec) @smguru fyi.

![image](https://user-images.githubusercontent.com/11935313/152457492-7f91af99-5e4b-4845-9bbc-fcafdb419737.png)

**Comment by markhepburn** [comment]
Thanks Anu!

**Comment by kitchenprinzessin3880** [comment]
process steps have been updated on UI and XML, see https://github.com/ternaustralia/TERN-ISO19115/blob/5c38b3fe7c6b6f19d308c732304826b70567545c/xml_template/TERN_ISO_Profile_v0_01.xml#L2758
