### ISSUE TITLE
Minor: comment refers to codeListValue=voice, but value is actually "facsimile"

### ISSUE THREAD

**Issue by markhepburn** [ternaustralia/TERN-ISO19115#15]
https://github.com/ternaustralia/TERN-ISO19115/blob/ec4ddd9aa9d6a8b5e2d73d9f50208127cdd39bc9/xml_template/TERN_ISO_Profile_v0_01.xml#L1017-L1020

**Comment by kitchenprinzessin3880** [comment]
Hi @markhepburn organization does not have a fax number. i have excluded the xml part. @smguru (fyi)
see https://github.com/ternaustralia/TERN-ISO19115/pull/16
