### ISSUE TITLE
About9: Correctness of comments

### ISSUE THREAD

**Issue by markhepburn** [ternaustralia/TERN-ISO19115#28]
The customCitation entry comments ("About9") may need correction or clarification:
https://github.com/ternaustralia/TERN-ISO19115/blob/273efff0e5b49e6e313cd0150b316f85da8f1b63/xml_template/TERN_ISO_Profile_v0_01.xml#L853-L858

Specifically:

- First comment still says it is required
- Penultimate comment says it supercedes the generated citation (my understanding it is appended to the generated citation)
- Is the final comment, about disabling DOI minting, correct?

**Comment by smguru** [comment]
Hello @markhepburn ,
the comments are wrong we will correct them following should be the correct statement, Don't worry about adding a logic of  disabling DOI mint if optional citation exist. @kitchenprinzessin3880 can you update the following text in next push


```

<!-- About9 ~ Documentation ~ Email 20210301 DV - custom citation is required and will write to othercitationdetails -->
  <!-- About9 ~ Help Text ~ The format of the standard citation is provided at  -->
  <!-- About9 ~ Help Text ~ https://ternaus.atlassian.net/wiki/spaces/TERNSup/pages/1223163969/How+is+the+citation+constructed+from+the+metadata  -->
  <!-- About9 ~ Help Text ~ provide text for additional citation information  -->
  <!-- About9 ~ Rule ~ If a custom citation is present this should append with the standard citation after identifier -->
  <!-- About9 ~ Rule ~ If a custom citation is present then DOI minting should be disabled and DOI should be created manually, the text in other citation needs to be mapped to a description of the datacite schema -->
```

**Comment by kitchenprinzessin3880** [comment]
@markhepburn @smguru i have updated the comment - https://github.com/ternaustralia/TERN-ISO19115/pull/29
